### ISSUE TITLE
Sometimes clicking on some games results in empty screen and makes application completely unusable afterwards.

### ISSUE THREAD

**Issue by ptkovsky** [streamlink/streamlink-twitch-gui#527]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [ ] I tried solving my issue by reading the project's wiki first.
- [ ] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

The issue is observed only from time to time. It happened today again so I decided to file a bug. It was first discovered while trying to open Quake Champions game section. So sometimes Twitch GUI acts weird after selecting this particular game. Note in this case that the bug also partially happens when you try to search for the term "quake" in general, using the search box. It gives you blank screen, but you can navigate elsewhere flawlessly afterwards.

### Expected / Actual behavior

Any GUI actions (games selection) are expected to be equal in terms of app stability, no matter when and how they are performed. Actual behavior is that the GUI becomes unresponsive and needs to be restarted to come back to normal operation.

### Reproduction steps

1. Find the desired game in Browse Games section or in My Games, however, you need to follow the game to be able to select it there. This assumes that you're logged in too.
2. Click on the game. Now this is when you get an empty screen bug. Note that I didn't find any other games acting like this and that the issue happens only from time to time (didn't tryhard much though).
3. Now try to click on any menu entry like My Live Streams or My Games. Sure, this section opens, but now you cannot really do anything afterwards as it refuses to open something or navigate elsewhere. For example, If you then click on a menu item, the small triangle will change its position but else nothing ever happens. If you try to open a stream, nothing happens. At this case you're stuck and need to restart the GUI.

### Environment details

Operating system and version: tested and reproducible on MacOS 10.13.2, Windows 7 Ultimate SP1. Guessing other systems like Linux are affected too.
Streamlink Twitch GUI version: 1.4.1
Streamlink version: 0.9.0
Configuration details: Nothing special, QuickTime Player playback on the MacOS system enabled in the GUI options, but don't think that this is relevant for the issue.

### Comments, logs, screenshots, etc.

Blank screen, ok? Hang. Can't click anywhere afterwards. Not sure how to find the log and if it's need. Can definitely make a screenshot if requested.

**Comment by bastimeyer** [comment]
> Blank screen

probably the same issue as reported and fixed in #517

> Not sure how to find the log

https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#--loglevel

**Comment by ptkovsky** [comment]
Looks like it. Btw, to find '$TMPDIR/streamlink-twitch-gui/logs' on MacOS you need to type in Terminal `echo $TMPDIR` and get some ridiculous pathing. Didn't know about this so was a little bit confused at first. So, after checking some of the log files this errors can be highlighted as pretty common:
```
[2018-01-07T17:21:59.008Z][error][Application]
TypeError: L.next is not a function

[2018-01-07T17:22:25.025Z][error][StreamingService]
Error: Process exited with code 130
```
and lots of:
```[2018-01-07T17:20:20.174Z][error][Application]
TypeError: Cannot read property 'querySelector' of null
```
and a few less of:
```
[2018-01-07T17:15:18.690Z][error][Application]
TypeError: Cannot read property 'off' of undefined
```

Anyway, will wait and and then figure out if that's fixed. The issue is pretty rare but it happens. Thanks!

**Comment by OneCrazyRussian** [comment]
The issue in #517 is actually not fixed, getting the same error on 1.4.1 version

Moreover the aforementioned issue itself is a regression from 1.3.1 version! I've downgraded back to 1.3.1 and it is not present at all. Except NW.js profile gave an expected downgrade error, but the games showed lists fine!

So I have 1.4.1, which does not work at all for some games, and 1.3.1, which timeouts on opening streams. Tough choice

**Comment by bastimeyer** [comment]
> The issue in #517 is actually not fixed, getting the same error on 1.4.1 version

The issue was fixed on December 12th by 83cadfc, `1.4.1` was released on November 19th. There is currently no newer release and you either have to live with the bug, downgrade, or compile the most recent version from the git master branch. I didn't have the time the past few days to continue my work on the latest upgrade which is blocking the progress towards a new release.

**Comment by PerceptionD** [comment]
I had the same issue. I found a workaround by filtering out non-English streams. Perhaps a non-English character in one of the stream titles was causing an issue?

**Comment by bastimeyer** [comment]
@PerceptionD 
> caused by a bug related to stream languages when a streamer has selected "other" as broadcasting language

https://github.com/streamlink/streamlink-twitch-gui/issues/517#issuecomment-351038509

**Comment by PerceptionD** [comment]
@bastimeyer 
My bad, I didn't read that.
