### ISSUE TITLE
Random white squares displayed by application

### ISSUE THREAD

**Issue by TheDromundKaas** [streamlink/streamlink-twitch-gui#814]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

1.12.0

### Streamlink version

2.2.0

### Operating system, environment and configuration details

                     ./o.                  dromundkaas@Pure 
                   ./sssso-                ---------------- 
                 `:osssssss+-              OS: EndeavourOS Linux x86_64 
               `:+sssssssssso/.            Host: MS-7C91 2.0 
             `-/ossssssssssssso/.          Kernel: 5.13.9-arch1-1 
           `-/+sssssssssssssssso+:`        Uptime: 6 hours, 27 mins 
         `-:/+sssssssssssssssssso+/.       Packages: 1301 (pacman) 
       `.://osssssssssssssssssssso++-      Shell: bash 5.1.8 
      .://+ssssssssssssssssssssssso++:     Resolution: 1920x1080, 1920x1080 
    .:///ossssssssssssssssssssssssso++:    DE: Plasma 5.22.4 
  `:////ssssssssssssssssssssssssssso+++.   WM: KWin 
`-////+ssssssssssssssssssssssssssso++++-   WM Theme: Breeze 
 `..-+oosssssssssssssssssssssssso+++++/`   Theme: Breeze Light [Plasma], Breeze [GTK2/3] 
   ./++++++++++++++++++++++++++++++/:.     Icons: breeze [Plasma], breeze [GTK2/3] 
  `:::::::::::::::::::::::::------``       Terminal: yakuake 
                                           CPU: AMD Ryzen 7 5800X (16) @ 3.800GHz 
                                           GPU: NVIDIA GeForce RTX 3070 
                                           Memory: 5762MiB / 32030MiB 

### Description

Since updating to 1.12.0 yesterday morning I have white squares displayed all over the main window (see attached screenshots). When scrolling (I have smooth scrolling disabled) the position and number can vary for each scroll tick, up to 3, sometimes there are none.

When enabling smooth scrolling, during the scroll there's a cascade of display of these squares until they stop switching when the smooth scroll tick is over.

The squares are not clickable, moving the mouse over them they usually switch, like if I would have scrolled using the mouse wheel.

Although I updated the BLOB NVidia driver in the same update it's probably not connected, as I closed and restarted STG after the update and had the problem immediately, without restarting.

STG is absolutely usable, it's just a little irritating.

![Screenshot_20210809_080743](https://user-images.githubusercontent.com/15246368/128853917-3b093b04-a28b-46a9-b286-89bb7e21bce6.png)
![Screenshot_20210809_080604](https://user-images.githubusercontent.com/15246368/128853931-6b79c54f-3cdf-40a4-a3d4-f45e9c98cb34.png)

**Comment by bastimeyer** [comment]
> I have white squares displayed all over the main window

This looks like a NW.js/Chromium rendering issue, probably related to GPU acceleration. These squares are not caused by any application code.

> Although I updated the BLOB NVidia driver in the same update it's probably not connected, as I closed and restarted STG after the update and had the problem immediately, without restarting.

On Arch and Arch-based systems, you'll have to reboot after updating your kernel. When updating the kernel, all kernel modules including out-of-tree modules (like Nvidia proprietary drivers for example) get removed from the file system for the current kernel version your system is running on, which means when something needs to be loaded after updating and not restarting that has not been loaded yet, those modules can't be found anymore. Please restart your system and see if these issues persist.

Other than that, there's not much I can do without seeing any debug logs from NW.js/Chromium.
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#nwjs--chromium-parameters

> DE: Plasma

Is this a wayland or X11 Plasma session?

The PKGBUILD in the AUR should cover all required dependencies when installing, and I don't think anything's missing there after the recent NW.js version bump.

**Comment by TheDromundKaas** [comment]
I already restarted since updating, the update was yesterday in the morning where I instantly had the issue, and after restarting/turning it off for the night, the issue is still there, so I have that covered.

I am running X11, the wayland support is still not great.

The attached log used the starting parameters

--enable-logging=stderr --v=1

I saw a few of the squares, scrolled down once, up once, then closed STG down.

[stg-logging.zip](https://github.com/streamlink/streamlink-twitch-gui/files/6961327/stg-logging.zip)

**Comment by bastimeyer** [comment]
> ```
> [173571:173571:0810/133623.502081:ERROR:shared_image_representation.cc(203)] Attempt to read from an uninitialized SharedImage
> [173580:173580:0810/133623.547993:VERBOSE1:layout_shift_tracker.cc(280)] in "chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/index.html#/games", 0x249000426f40:LayoutNGBlockFlow (positioned) HEADER moved from "933.922,130.172 222.109x29.3125" to "933.922,127.172 222.109x29.3125" (visible from "934,130 222x29" to "934,130 222x26")
> [173580:173580:0810/133623.548106:VERBOSE1:layout_shift_tracker.cc(453)] in "chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/index.html#/games", viewport was 0.323661% impacted with distance fraction 0.0015625
> [173580:173580:0810/133623.548207:VERBOSE1:layout_shift_tracker.cc(529)] in "chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/index.html#/games", layout shift of 5.0572e-06 reported; cumulative score is 5.0572e-06
> ```

These are the only relevant lines from what it looks like, but there's not much useful information.

----

I've pushed the `nwjs-55` branch to the repo which bumps the NW.js version from 0.52.2 to 0.55.0 (uses the latest Chromium version).

Could you please run the app from this branch and see whether this fixes your issue?
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.12.0/CONTRIBUTING.md#developing-and-building

```bash
sudo pacman -S git nodejs yarn

git clone --branch nwjs-55 https://github.com/streamlink/streamlink-twitch-gui.git
cd streamlink-twitch-gui
yarn install --pure-lockfile
yarn run grunt
```

The branch currently does not build successfully because the version bump made some time-related test cases fail (dependency issue). A development build `yarn run grunt` should work just fine though.

**Comment by TheDromundKaas** [comment]
The build was successful, but the problem persists. The version number displayed in About is now v1.12.0+2.g5e1de157. NW.js is 0.55.0.

**Comment by bastimeyer** [comment]
Have you checked if 1.11.0 does have the same problem after your system upgrade?

Please install the previous version, either from your package cache or by building it from the AUR:

```bash
git clone https://aur.archlinux.org/streamlink-twitch-gui.git
cd streamlink-twitch-gui
git checkout 7840de35d56d7becddbb240889b9f84afacc3ccb  # the PKGBUILD commit for v1.11.0
makepkg -si
/usr/bin/streamlink-twitch-gui
```

If the issue persists, then it's a problem on your system.
If not, then this needs to be reproduced in NW.js and reported upstream.

**Comment by TheDromundKaas** [comment]
Done. No issue visible, I tried starting multiple times, scrolled through the games each time, entered a game each time, no problems visible. Attached is the log as above from the 1.11.0.

If I can help any other way, let me know.

[stg-logging.zip](https://github.com/streamlink/streamlink-twitch-gui/files/6962104/stg-logging.zip)

**Comment by bastimeyer** [comment]
- Do you have the same issues in regular Chromium or Chromium-based browsers?
- Have you tried disabling GPU acceleration via `--disable-gpu`?
- Do you have any custom nvidia settings which could interfere with Chromium's rendering?

Unless this isn't caused by something very specific on your system, then this can probably be reproduced in NW.js with a hopefully simple demo application.

SDK builds of NW.js can be downloaded here:
https://nwjs.io/downloads/
And the unmaintained / outdated docs can be found here:
https://docs.nwjs.io/en/latest/For%20Users/Getting%20Started/

I can't really help with this because I don't have any glitches with my AMD GPU and I don't know what would be responsible for this.

What's interesting about your screenshots is that the glitches are in a grid of squares which lay on top of the entire viewport. That means that the app content is not the culprit here.

----

Regarding the `nwjs-55` branch, I've pushed some changes which fix the tests so that it can be built again via `yarn run grunt release`.
https://github.com/streamlink/streamlink-twitch-gui/commits/nwjs-55
https://github.com/streamlink/streamlink-twitch-gui/actions/runs/1117039128

**Comment by TheDromundKaas** [comment]
I thank you for your help, and the issue is closed. It's highly unlikely that I develop the skills to create a reproducible for this issue, so I'll let it ride for now, but keep an eye on the issue tracker for NW.js.

**Comment by bastimeyer** [comment]
One thing you could check is `chrome://gpu` in NW.js. The vanilla NW.js SDK build allows you to enter this URL, just like in your web browser.

In Streamlink Twitch GUI, this is disabled of course, but it can still be accessed via the remote debugging protocol. When you run a development build via `yarn run grunt`, http://localhost:8888 can be opened in your web browser and you will see the running NW.js page(s), where you have the remote viewport with an additional address bar and remote dev tools.
